# Generated by Django 4.2.1 on 2023-11-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kvantorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('patronymic', models.CharField(blank=True, max_length=10)),
                ('Birthday', models.DateTimeField(max_length=15)),
                ('is_excellent', models.BooleanField(max_length=15)),
                ('is_not_excellent', models.BooleanField(max_length=15)),
            ],
        ),
    ]
