# Generated by Django 4.2.1 on 2023-11-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humster', '0002_kvantorium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=15)),
                ('is_interesting', models.BooleanField(max_length=15)),
                ('is_not_interesting', models.BooleanField(max_length=15)),
            ],
        ),
    ]
